### ISSUE TITLE
JSON-RPC method not found. code:-32601

### ISSUE THREAD

**Issue by duktig666** [paritytech/substrate#11509]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

env：parity/polkadot:v0.9.22
```
network: polkadot
  p2pPort: 30333
  validator: false
  syncMode: fast
  pruning: true
  retainedBlocks: 1024
  logging: info
  telemetry: false
  telemetryURL: wss://telemetry.polkadot.io/submit/0
  prometheus: true
  prometheusPort: 9615
  rpc: true
  rpcPort: 9933
  rpcMethods: unsafe
  ws: true
  wsPort: 9944
  corsDomains:
    - '*'
  resources:
    cpu: "4"
    cpuLimit: "8"
    memory: 4Gi
    memoryLimit: 8Gi
    storage: 80Gi
    storageClass: gp2
```

execute code:
```
curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "net_peerCount", "params":[]}' http://localhost:9933
```

error:
```
{"code":-32601,"message":"Method not found"}
```

https://substrate.stackexchange.com/questions/2803/json-rpc-method-not-found-code-32601
It's my question.

### Steps to reproduce

deploy polkadot don't access JSON-RPC method —— net_peerCount
