### ISSUE TITLE
rustfmt configuration file

### ISSUE THREAD

**Issue by ivanceras** [paritytech/substrate#5456]
There is no `rustfmt.toml`used in the code, except for [`.editorconfig`](https://github.com/paritytech/substrate/blob/master/.editorconfig)
I'm trying to replicate the configurations used in `substrate` code to `rustfmt.toml`, 

```toml
unstable_features = true
max_width = 100
# substrate devs uses hardtabs as convention
hard_tabs = true
# prevent reorder imports
reorder_imports = false
# prevent reorder of module declarations
reorder_modules = false
imports_layout = "Mixed"
use_small_heuristics = "Max"
```
but everytime I invoke `cargo fmt` there are a lot of changes to the code.  
I'm curious to find out how the substrate devs are synchronizing their format configurations.
