### ISSUE TITLE
`substrate-wasm-builder-runner` causes the verification step of `cargo publish` to fail

### ISSUE THREAD

**Issue by stephaneyfx** [paritytech/substrate#7116]
## Issue
`substrate-wasm-builder-runner` causes the verification step of `cargo publish` to fail. This appears to be due to it generating a `Cargo.lock` in the directory containing a copy of the source tree which `cargo publish` uses to verify builds.

## Reproduction steps
```sh
cargo new --lib try-wasm
cd try-wasm
```

Edit `Cargo.toml` so that it looks like this:
```toml
[package]
name = "try-wasm"
version = "0.1.0"
authors = ["Stephane Raux <x@x.x>"]
edition = "2018"

[build-dependencies]
substrate-wasm-builder-runner = { version = "1.0.6" }
```

Create `build.rs` with the contents:
```rust
use substrate_wasm_builder_runner::WasmBuilder;

fn main() {
    WasmBuilder::new()
        .with_current_project()
        .with_wasm_builder_from_crates("2.0.0")
        .export_heap_base()
        .import_memory()
        .build();
}
```

Run:
```sh
cargo publish --dry-run --manifest-path Cargo.toml --allow-dirty
```

## Expected result
Publication succeeds.

## Actual result
Publication fails with:
```
error: failed to verify package tarball

Caused by:
  Source directory was modified by build.rs during cargo publish. Build scripts should not modify anything outside of OUT_DIR.
  Added: /home/x/src/tmp/try-wasm/target/package/try-wasm-0.1.0/Cargo.lock

  To proceed despite this, pass the `--no-verify` flag.
```

## Workaround
In our case, the runtime crate is part of a workspace and so `concat!(env!("CARGO_MANIFEST_DIR"), "/Cargo.lock")` does not exist except during the verification before publication, meaning we can delete it in `build.rs` after calling `WasmBuilder::build`.
