### ISSUE TITLE
Benchmarking - WASM build error due to "getrandom"

### ISSUE THREAD

**Issue by mustermeiszer** [paritytech/substrate#9595]
Hi

I am getting a build error when running a release build with `runtime-benchmarks` features on. I bet there is something wrong with my Cargo.toml file. I only have this error when building with benchmarks features. The normal wasm build for the runtime has no problems. 

The error solely occurs when I integrate one specific new pallet. So I think it is due to the dependencies of this pallet. As the error indicates that the `Js` feature is not activated in the `getrandom` lib, I directly integrated the dependency with the feature flag on, but then I am getting another error in some frame pallet, namely `sp-npos-elections`. 

If you have the time, I would appreciate a hint or some guidance here. Errors are shown below.

## Here is my `Cargo.toml` of the problematic pallet:

```
[package]
name = 'pallet-crowdloan-claim'
description = 'Module for processing crowdloan claim rewards.'
authors = ['The Centrifugians Tribe']
edition = '2018'
homepage = 'https://centrifuge.io'
license = "LGPL-3.0"
repository = 'https://github.com/centrifuge/centrifuge-chain'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
# General dependencies
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
log = { version = "0.4.14", default-features = false }
lazy_static = "1.4.0"
serde = { version = "1.0.119" }

# Substrate depenedencies
frame-support = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "master" }
frame-system = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "master" }
frame-benchmarking = { git = "https://github.com/centrifuge/substrate", default-features = false , optional = true , branch = "master" }
pallet-balances = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "master" }
sp-core = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "master" }
sp-runtime = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "master" }
sp-std = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "master" }
sp-io = { git = "https://github.com/centrifuge/substrate", default-features = false , optional = true, branch = "master" }
getrandom = { version = "0.2", features = ["js"], optional = true }

# Local dependencies
trait-crowdloan-reward = { path= '../../libs/trait-crowdloan-reward', default_features = false }

[dev-dependencies]
sp-trie = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "master" }
sp-keyring = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "master" }
pallet-vesting = { git = "https://github.com/centrifuge/substrate", default-features = true, branch = "master" }
pallet-crowdloan-reward = { path='../crowdloan-reward', default_features = false }
hex = { version="0.4.3", default_features = true}

[features]
default = ['std']
runtime-benchmarks = ['frame-benchmarking', 'sp-core/std', 'frame-support/runtime-benchmarks', 'sp-io/std', 'getrandom/js']
std = [
  'codec/std',
  'frame-support/std',
  'trait-crowdloan-reward/std',
  'frame-system/std',
  'log/std',
  'pallet-balances/std',
  'sp-io/std',
  'sp-std/std',
  'sp-core/std',
  'frame-benchmarking',
]

```

## `Cargo.toml` of the runtime itself
```toml
[package]
name = "development-runtime"
version = "2.0.0"
authors = ["Centrifuge <admin@centrifuge.io>"]
edition = "2018"
build = "build.rs"
license = "LGPL-3.0"
homepage = "https://centrifuge.io/"
repository = "https://github.com/centrifuge/centrifuge-chain"

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
integer-sqrt = { version = "0.1.2" }
safe-mix = { version = "1.0", default-features = false }
smallvec = "1.4.0"
static_assertions = "1.1.0"
hex-literal = { version = "0.2.1", optional = true }
rustc-hex = { version = "2.0", optional = true }
serde = { version = "1.0.102", optional = true }

# parachain
parachain-info = { git = "https://github.com/centrifuge/cumulus", default-features = false, branch = "centrifuge" }
cumulus-pallet-parachain-system = { git = "https://github.com/centrifuge/cumulus", default-features = false, branch = "centrifuge" }
cumulus-primitives-core = {git = "https://github.com/centrifuge/cumulus", default-features = false, branch = "centrifuge" }
cumulus-primitives-utility = {git = "https://github.com/centrifuge/cumulus", default-features = false, branch = "centrifuge" }
cumulus-pallet-xcm = {git = "https://github.com/centrifuge/cumulus", default-features = false, branch = "centrifuge" }
cumulus-pallet-xcmp-queue = {git = "https://github.com/centrifuge/cumulus", default-features = false, branch = "centrifuge" }
cumulus-pallet-dmp-queue = {git = "https://github.com/centrifuge/cumulus", default-features = false, branch = "centrifuge" }
cumulus-pallet-aura-ext = {git = "https://github.com/centrifuge/cumulus", default-features = false, branch = "centrifuge" }
cumulus-primitives-timestamp = {git = "https://github.com/centrifuge/cumulus", default-features = false, branch = "centrifuge" }


# polkadot dependencies
polkadot-parachain = { git = "https://github.com/centrifuge/polkadot", default-features = false , branch = "centrifuge" }
polkadot-runtime-common = { git = "https://github.com/centrifuge/polkadot", default-features = false , branch = "centrifuge" }
xcm = { git = "https://github.com/centrifuge/polkadot", default-features = false , branch = "centrifuge" }
pallet-xcm = { git = "https://github.com/centrifuge/polkadot", default-features = false , branch = "centrifuge" }
xcm-executor = { git = "https://github.com/centrifuge/polkadot", default-features = false , branch = "centrifuge" }
xcm-builder = { git = "https://github.com/centrifuge/polkadot", default-features = false , branch = "centrifuge" }

# primitives
sp-authority-discovery = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
sp-consensus-babe = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
sp-block-builder = { git = "https://github.com/centrifuge/substrate",  default-features = false, branch = "master" }
sp-inherents = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
node-primitives = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
sp-offchain = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
sp-core = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
sp-io = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
sp-std = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
sp-api = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
sp-runtime = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
sp-staking = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
sp-session = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
sp-transaction-pool = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
sp-version = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
sp-arithmetic = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
sp-consensus-aura = { git = "https://github.com/centrifuge/substrate", default-features = false, branch = "master" }

# frame dependencies
frame-executive = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
frame-support = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
frame-system = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
frame-benchmarking = { git = "https://github.com/centrifuge/substrate",  default-features = false , optional = true , branch = "master" }
frame-system-rpc-runtime-api = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-authority-discovery = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-authorship = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-babe = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-balances = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-collective = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-democracy = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-elections-phragmen = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-grandpa = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-im-online = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-indices = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-membership = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-multisig = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-offences = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-proxy = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-randomness-collective-flip = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-session = { git = "https://github.com/centrifuge/substrate",  default-features = false, features = ["historical"] , branch = "master" }
pallet-staking = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-staking-reward-curve = { git = "https://github.com/centrifuge/substrate", branch = "master" }
pallet-timestamp = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-utility = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-transaction-payment = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-identity = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-scheduler = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-vesting = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-sudo = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-aura = { git = "https://github.com/centrifuge/substrate", default-features = false, branch = "master" }
pallet-society = { git = "https://github.com/centrifuge/substrate", default-features = false, branch = "master" }
max-encoded-len = { git = "https://github.com/centrifuge/substrate", default-features = false, features = [ "derive" ] , branch = "master" }

runtime-common = { path = "../common", default-features = false }

pallet-anchors = { path = "../../pallets/anchors", default-features = false }
pallet-fees = { path = "../../pallets/fees", default-features = false }
pallet-claims = { path = "../../pallets/claims", default-features = false }
pallet-crowdloan-claim = { path = "../../pallets/crowdloan-claim", default-features = false }
pallet-crowdloan-reward = { path = "../../pallets/crowdloan-reward", default-features = false }

[build-dependencies]
substrate-wasm-builder = "3.0.0"

[features]
default = ["std"]
std = [
    "pallet-crowdloan-claim/std",
    "pallet-crowdloan-reward/std",
    "sp-authority-discovery/std",
    "pallet-authority-discovery/std",
    "pallet-authorship/std",
    "sp-consensus-babe/std",
    "pallet-babe/std",
    "pallet-balances/std",
    "sp-block-builder/std",
    "codec/std",
    "pallet-collective/std",
    "pallet-democracy/std",
    "pallet-elections-phragmen/std",
    "frame-executive/std",
    "pallet-grandpa/std",
    "pallet-im-online/std",
    "pallet-indices/std",
    "sp-inherents/std",
    "pallet-membership/std",
    "pallet-multisig/std",
    "pallet-identity/std",
    "pallet-scheduler/std",
    "node-primitives/std",
    "sp-offchain/std",
    "pallet-offences/std",
    "pallet-proxy/std",
    "sp-core/std",
    "pallet-randomness-collective-flip/std",
    "sp-std/std",
    "serde",
    "pallet-session/std",
    "sp-api/std",
    "sp-runtime/std",
    "sp-staking/std",
    "pallet-staking/std",
    "sp-session/std",
    "frame-support/std",
    "frame-system-rpc-runtime-api/std",
    "frame-system/std",
    "pallet-timestamp/std",
    "pallet-transaction-payment-rpc-runtime-api/std",
    "pallet-transaction-payment/std",
    "pallet-vesting/std",
    "sp-transaction-pool/std",
    "pallet-utility/std",
    "sp-version/std",
    "sp-arithmetic/std",
    "sp-io/std",
    "rustc-hex",
    "safe-mix/std",
    "cumulus-pallet-parachain-system/std",
    "cumulus-primitives-timestamp/std",
    "cumulus-pallet-xcmp-queue/std",
    "parachain-info/std",
    "xcm/std",
    "xcm-executor/std",
    "xcm-builder/std",
    "cumulus-pallet-xcm/std",
    "cumulus-pallet-aura-ext/std",
    "pallet-aura/std",
    "sp-consensus-aura/std",
    "max-encoded-len/std",
    "pallet-fees/std",
    "pallet-anchors/std",
    "pallet-claims/std",
    "pallet-sudo/std",
    "pallet-society/std",
    "runtime-common/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
    "hex-literal",
    "pallet-fees/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "pallet-xcm/runtime-benchmarks",
    "xcm-builder/runtime-benchmarks",
    "pallet-collective/runtime-benchmarks",
    "pallet-society/runtime-benchmarks",
    "pallet-crowdloan-reward/runtime-benchmarks",
    "pallet-crowdloan-claim/runtime-benchmarks",
]

# A feature that should be enabled when the runtime should be build for on-chain
# deployment. This will disable stuff that shouldn't be part of the on-chain wasm
# to make it smaller like logging for example.
on-chain-release-build = [
    "sp-api/disable-logging",
]

```

## Command I am running
```shell
cargo +nightly run --release --features runtime-benchmarks -- benchmark --chain=devel-local --steps=100 --repeat=200 --pallet=pallet-crowdloan-claim '--extrinsic=*' --execution=wasm --wasm-execution=compiled --heap-pages=4096 --output=pallets/crowdloan-claim/src/weight.rs --template=./scripts/frame-weight-template.hbs
   Compiling development-runtime v2.0.0 (/Users/frederik/Projects/centrifuge-chain/runtime/development)
``` 

## Error without direct activation of `getrandom` dependency:
```bash
  Compiling cumulus-client-consensus-common v0.1.0 (https://github.com/centrifuge/cumulus?branch=centrifuge#e6768b3e)
   Compiling polkadot-client v0.9.8 (https://github.com/centrifuge/polkadot?branch=centrifuge#660f3906)
   Compiling cumulus-primitives-parachain-inherent v0.1.0 (https://github.com/centrifuge/cumulus?branch=centrifuge#e6768b3e)
   Compiling cumulus-client-network v0.1.0 (https://github.com/centrifuge/cumulus?branch=centrifuge#e6768b3e)
   Compiling polkadot-service v0.9.8 (https://github.com/centrifuge/polkadot?branch=centrifuge#660f3906)
   Compiling cumulus-client-consensus-aura v0.1.0 (https://github.com/centrifuge/cumulus?branch=centrifuge#e6768b3e)
   Compiling cumulus-client-consensus-relay-chain v0.1.0 (https://github.com/centrifuge/cumulus?branch=centrifuge#e6768b3e)
   Compiling cumulus-pallet-parachain-system v0.1.0 (https://github.com/centrifuge/cumulus?branch=centrifuge#e6768b3e)
   Compiling cumulus-client-collator v0.1.0 (https://github.com/centrifuge/cumulus?branch=centrifuge#e6768b3e)
error: failed to run custom build command for `development-runtime v2.0.0 (/Users/frederik/Projects/centrifuge-chain/runtime/development)`

Caused by:
  process didn't exit successfully: `/Users/frederik/Projects/centrifuge-chain/target/release/build/development-runtime-b1140cf8f87a9b36/build-script-build` (exit status: 1)
  --- stdout
  Information that should be included in a bug report.
  Executing build command: "/Users/frederik/.rustup/toolchains/nightly-x86_64-apple-darwin/bin/cargo" "-Zfeatures=build_dep" "rustc" "--target=wasm32-unknown-unknown" "--manifest-path=/Users/frederik/Projects/centrifuge-chain/target/release/wbuild/development-runtime/Cargo.toml" "--color=always" "--release"
  Using rustc version: rustc 1.56.0-nightly (3d0774d0d 2021-08-18)


  --- stderr
  warning: flag `-Z features` has been stabilized in the 1.51 release, and is no longer necessary
    The new feature resolver is now available by specifying `resolver = "2"` in Cargo.toml.
    See https://doc.rust-lang.org/nightly/cargo/reference/features.html#feature-resolver-version-2 for more information.

     Compiling getrandom v0.2.3
  error: the wasm32-unknown-unknown target is not supported by default, you may need to enable the "js" feature. For more information see: https://docs.rs/getrandom/#webassembly-support
     --> /Users/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.3/src/lib.rs:219:9
      |
  219 | /         compile_error!("the wasm32-unknown-unknown target is not supported by \
  220 | |                         default, you may need to enable the \"js\" feature. \
  221 | |                         For more information see: \
  222 | |                         https://docs.rs/getrandom/#webassembly-support");
      | |_________________________________________________________________________^

  error[E0433]: failed to resolve: use of undeclared crate or module `imp`
     --> /Users/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.3/src/lib.rs:246:5
      |
  246 |     imp::getrandom_inner(dest)
      |     ^^^ use of undeclared crate or module `imp`

  For more information about this error, try `rustc --explain E0433`.
  error: could not compile `getrandom` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
```
## Error with direct activation of `getrandom` dependency:
```shell
     Compiling max-encoded-len v3.0.0 (https://github.com/centrifuge/substrate?branch=master#1b758b2a)
     Compiling sp-runtime-interface v3.0.0 (https://github.com/centrifuge/substrate?branch=master#1b758b2a)
     Compiling memory-db v0.26.0
     Compiling sp-core v3.0.0 (https://github.com/centrifuge/substrate?branch=master#1b758b2a)
     Compiling sp-trie v3.0.0 (https://github.com/centrifuge/substrate?branch=master#1b758b2a)
     Compiling sp-keystore v0.9.0 (https://github.com/centrifuge/substrate?branch=master#1b758b2a)
     Compiling sp-inherents v3.0.0 (https://github.com/centrifuge/substrate?branch=master#1b758b2a)
     Compiling frame-metadata v13.0.0 (https://github.com/centrifuge/substrate?branch=master#1b758b2a)
     Compiling sp-npos-elections v3.0.0 (https://github.com/centrifuge/substrate?branch=master#1b758b2a)
     Compiling sp-state-machine v0.9.0 (https://github.com/centrifuge/substrate?branch=master#1b758b2a)
  error: cannot find macro `vec` in this scope
    --> /Users/frederik/.cargo/git/checkouts/substrate-c08550cb428dbcc9/1b758b2/primitives/npos-elections/src/phragmms.rs:52:20
     |
  52 |     let mut winners = vec![];
     |                       ^^^
     |
     = note: consider importing one of these items:
             codec::alloc::vec
             crate::sp_std::vec
             sp_std::vec

  error: could not compile `sp-npos-elections` due to previous error
  warning: build failed, waiting for other jobs to finish...
  error: build failed
warning: build failed, waiting for other jobs to finish...
error: build failed
```
